---
- name: Install Grafana
  apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present
- name: Add Grafana repository
  apt_repository:
    repo: 'deb https://packages.grafana.com/oss/deb stable main'
    state: present
    update_cache: yes
- name: Install Grafana
  apt:
    name: grafana
    state: present
    update_cache: yes    
  become: yes

- name: Grafana configuration file copy
  template:
    src: grafana.conf.j2
    dest: /etc/grafana/grafana.ini
  notify: restart_grafana
  become: yes

- name: Grafana server started
  systemd:
    name: grafana-server
    enabled: true
    state: started
  become: yes

- name: Check if Grafana is accessible
  uri:
    url: http://127.0.0.1:3000
    method: GET
    status_code: 200

